### ISSUE TITLE
play test action items

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#374]
**4/8 - internal play test**
- [x] waiting lobby: problems with indefinitely waiting for game to start
- [x] color coding accomplishments to mark them as purchased doesn't work
- [x] ready to advance button - isn't obvious enough that player is 'done', needs to be more conspicuous
- [x] trade request modal - add name under player avatars
- [x] trade request acceptances/rejections aren't persisted to inventory but trade data shows accurately on mars log
- [ ] disconnection problems - chat and time freezing for player when the player disconnects from game
- [x] system health - remove from inventory popup and display notification for contributed system health somewhere else
- [x] discard phase: when player discards all accomplishments, auto-set player readiness
- [ ] game is lagging - optimize amount of local storage or memory used
- [x] add round markers or partitions on mars log to distinguish mars log messages by round and make messages more digestible

**3/27**
- [x] trades don't seem to be accurate (e.g. if player is supposed to receive something from a trade, it is recorded in mars log but doesn't update in inventory)
- [x] clock stopped working
- [x] perpetual waiting in the waiting lobby - never transitioned into the game 
- [x] ~~interchange chat with mars log in new UI~~ resolved by #379 
- [ ] write trade validations

**3/12**
- [x] ~~trade from previous round still had selected information (e.g., selected curator the previous round, next round curator was still selected)~~ resolved by #347

- [x] ~~received 2 events at exactly 65 upkeep. It should be 35 <= upkeep < 65 and 3 events at < 35~~ resolved by #348 
- [ ] allow for altruistic trades (0 for X>1 or X>1 for 0, but no 0 for 0)
- [x] ~~in general, the UI is too small and we might need to think of a major redo that maximizes the layout for the action you want to take when you select it #351~~ resolving in [refactor-ui](https://github.com/virtualcommons/port-of-mars/tree/refactor-ui)
- [x] tutorial flow should have the player click "Done" to terminate every phase to highlight the habit of clicking Done after completing an action
- [x] final mars log should be in reverse descending order (most recent first, oldest last)
- [x] vote log events should be set the category to the event type that generated the vote
- [x] ~~mars log system health modifications need to be finer grained: `standard wear and tear reduced system health by 25. Your group invested a total of Y into system health last round. Event Y reduced system health by Z.`~~ resolved by  d7e4bd9

**Comment by Nick42791** [comment]
I can take the final mars log issue

**Comment by chrstngyn** [comment]
@Nick42791 @lfaivre updated this with notes and action items from today

**Comment by Nick42791** [comment]
@chrstngyn 
I can work on the color coding for accomplishments, make the advance button more conspicuous, add the names of the roles in the trade modal, and auto complete phases that you can't do anything in.

**Comment by Nick42791** [comment]
we might also add that some of the phases are coming out of their bounding boxes, but I think @lfaivre is already working on that.

**Comment by lfaivre** [comment]
>  trade request modal - add name under player avatars

fixed in the current build

**Comment by lfaivre** [comment]
> color coding accomplishments to mark them as purchased doesn't work

this appears to be working, is there something else that needs to be addressed here?

**Comment by lfaivre** [comment]
> ready to advance button - isn't obvious enough that player is 'done', needs to be more conspicuous

@Nick42791 added an effect, and font size and color was modified to increase visibility. seemed to work better in the latest play test

**Comment by lfaivre** [comment]
> system health - remove from inventory popup and display notification for contributed system health somewhere else

contributed system health information is removed by default in a [recent pr](https://github.com/virtualcommons/port-of-mars/pull/432). we should discuss at some point how better to display this information

**Comment by lfaivre** [comment]
> discard phase: when player discards all accomplishments, auto-set player readiness

this was done, and then undone by @Nick42791

**Comment by chrstngyn** [comment]
i think this issue can be closed. we've separated any lingering issues from the play tests into individual issues. @alee @cpritcha ?

**Comment by chrstngyn** [comment]
action items have been split into individual issues
