### ISSUE TITLE
responsiveness + usability task list

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#743]
- [ ] restyle modals so there is style uniformity
- [ ] hero and pariah event ui off center
- [ ] dashboard ui
- [ ] consent form ui
- [ ] breakdown of trust ui should be refined
- [ ] spin button sizes don't respond well to small screens sizes
- [ ] refine padding + margins of game board components
- [ ] buttons underneath player avatar need to be refined - seem to be off center

**Comment by chrstngyn** [comment]
we should probably deprecate setting custom styles on html and bootstrap components e.g. style="..." and move those t _variables.scss or main.scss for the sake of maintainability

**Comment by alee** [comment]
if it gets used over and over, definitely - I'm not a fan of the explicit styles either. If it's just a one off putting it in the local .vue `<style scoped>` section is fine as well

**Comment by alee** [comment]
trade UI still has whited out disabled investment buttons for some reason, looks like we need to apply the same changes made in InvestmentCard.vue to TradeOptions.vue @chrstngyn

**Comment by alee** [comment]
New round screen:

![image](https://user-images.githubusercontent.com/22534/140187569-4031eae7-94be-400f-b1f1-15aaef702f59.png)

**Comment by alee** [comment]
investment screen:
![image](https://user-images.githubusercontent.com/22534/140187991-90400f7e-e3db-471d-8ad7-a2d05dd18bc2.png)

**Comment by alee** [comment]
minor issues: mars log box should be same width as chat

![image](https://user-images.githubusercontent.com/22534/140563291-a360dd52-5500-4357-a7b3-06fd0660b9bb.png)

**Comment by alee** [comment]
align costs in investment card
![image](https://user-images.githubusercontent.com/22534/140563355-ee54afb7-ca03-46a3-87ee-e8adaa4e3006.png)

**Comment by alee** [comment]
move system health report into the Information tab in NewRound
